import SwiftUI

// Color extensions are auto-generated by Xcode from the Asset Catalog (GeneratedAssetSymbols.swift):
// Color.deepSpaceBackground, Color.astralGold, Color.orbitGreen, Color.starMist, Color.flareCoral
